#library specific to Raster_to_region.R

library(raster)
library(sp)
library(rgdal)
library(maptools)
library(rgeos)
library(dplyr)
library(sf)
library(openxlsx)

# download packages
# install.packages('raster')
# install.packages('rgdal')
# install.packages('sp')
# install.packages('maptools')
# install.packages('rgeos')
# install.packages('dplyr')
# install.packages('ggplot2')
# install.packages('sf')
# install.packages('ggplot2')
# install.packages('ggmaps')
# install.packages('maps')
# install.packages('maptools')
# install.packages('plyr')
# install.packages('openxlsx')
# install.packages('gridExtra')
# install.packages('geomerge')
# install.packages('zip')